services:
  - type: web
    name: spelinx
    runtime: node
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: FRONTEND_URL
        fromService:
          type: web
          name: spelinx
          property: host
      - key: ALLOWED_ORIGINS
        fromService:
          type: web
          name: spelinx
          property: host